"""m01 twin initial

Revision ID: 6a49290df5f0
Revises: 
Create Date: 2026-09-23 15:43:56.196137
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.core.db  # noqa: F401  (custom column types)


revision: str = '6a49290df5f0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('m01_twin',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ts', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'ts', name=op.f('pk_environment_events'))
    )
    with op.batch_alter_table('environment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_events_site_id'), ['site_id'], unique=False)

    op.create_table('machine_confirmations',
    sa.Column('confirmation_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('confirmation_id', name=op.f('pk_machine_confirmations'))
    )
    with op.batch_alter_table('machine_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_confirmations_operator_id'), ['operator_id'], unique=False)

    op.create_table('machine_state_changes',
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('ts', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('from_mode', sa.String(length=16), nullable=True),
    sa.Column('to_mode', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('machine_id', 'ts', name=op.f('pk_machine_state_changes'))
    )
    op.create_table('machine_telemetry',
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('ts', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('engine_hours', sa.Float(), nullable=False),
    sa.Column('fuel_pct', sa.Float(), nullable=False),
    sa.Column('fuel_rate_lph', sa.Float(), nullable=False),
    sa.Column('load_cycles', sa.Integer(), nullable=False),
    sa.Column('idle_seconds', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('rpm', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('operating_mode', sa.String(length=16), nullable=False),
    sa.Column('seatbelt', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('machine_id', 'ts', name=op.f('pk_machine_telemetry'))
    )
    op.create_table('operator_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ts', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'ts', name=op.f('pk_operator_events'))
    )
    with op.batch_alter_table('operator_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_events_operator_id'), ['operator_id'], unique=False)

    op.create_table('precheck_results',
    sa.Column('precheck_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('failed_items', sa.JSON(), nullable=False),
    sa.Column('submitted_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('precheck_id', name=op.f('pk_precheck_results'))
    )
    with op.batch_alter_table('precheck_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precheck_results_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precheck_results_operator_id'), ['operator_id'], unique=False)

    op.create_table('precheck_templates',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('machine_type', sa.String(length=32), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_precheck_templates')),
    sa.UniqueConstraint('machine_type', name=op.f('uq_precheck_templates_machine_type'))
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('planned_start', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('planned_end', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('assistance', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('twin_intelligence',
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source_event_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('operator_id', 'slot', name=op.f('pk_twin_intelligence'))
    )
    op.create_table('twin_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('taken_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('twin', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_twin_snapshots'))
    )
    with op.batch_alter_table('twin_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_snapshots_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_twin_snapshots_taken_at'), ['taken_at'], unique=False)

    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_assignments_task_id_tasks')),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('pk_assignments'))
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_task_id'), ['task_id'], unique=False)

    op.create_table('task_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actual_start', backend.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actual_end', backend.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('paused_at', backend.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('pause_duration_s', sa.Float(), nullable=False),
    sa.Column('start_load_cycles', sa.Integer(), nullable=True),
    sa.Column('precheck_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name=op.f('fk_task_sessions_assignment_id_assignments')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_task_sessions_task_id_tasks')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_task_sessions'))
    )
    with op.batch_alter_table('task_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_sessions_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_sessions_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_sessions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###
    _create_hypertables()


HYPERTABLES = ["machine_telemetry", "machine_state_changes", "operator_events", "environment_events"]


def _create_hypertables() -> None:
    """TimescaleDB hypertables on PostgreSQL (no-op on SQLite lite mode). Primary keys include `ts`."""
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    for table in HYPERTABLES:
        op.execute(f"SELECT create_hypertable('{table}', 'ts', if_not_exists => TRUE, migrate_data => TRUE)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_sessions_operator_id'))
        batch_op.drop_index(batch_op.f('ix_task_sessions_machine_id'))

    op.drop_table('task_sessions')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_task_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_operator_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_machine_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('twin_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_snapshots_taken_at'))
        batch_op.drop_index(batch_op.f('ix_twin_snapshots_operator_id'))

    op.drop_table('twin_snapshots')
    op.drop_table('twin_intelligence')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_site_id'))

    op.drop_table('tasks')
    op.drop_table('precheck_templates')
    with op.batch_alter_table('precheck_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precheck_results_operator_id'))
        batch_op.drop_index(batch_op.f('ix_precheck_results_machine_id'))

    op.drop_table('precheck_results')
    with op.batch_alter_table('operator_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_events_operator_id'))

    op.drop_table('operator_events')
    op.drop_table('machine_telemetry')
    op.drop_table('machine_state_changes')
    with op.batch_alter_table('machine_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_confirmations_operator_id'))

    op.drop_table('machine_confirmations')
    with op.batch_alter_table('environment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_events_site_id'))

    op.drop_table('environment_events')
    # ### end Alembic commands ###
