#!/usr/bin/env python3
"""Contract tooling. Run from the repo root: ``uv run python scripts/contracts.py <cmd>``.

  check           Validate every JSON Schema under contracts/, every example against its schema,
                  and every OpenAPI file's basic shape. Non-zero exit on any problem.
  export          Regenerate contracts/openapi/argus-api.yaml from the backend app, plus every JSON document a
                  capability generates from its models via ``contract_documents()`` in its wiring.py
                  (twin schema, event payload schemas, Copilot tool schemas).
  export --check  Fail if committed generated contracts differ from what the code generates (CI).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml
from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
OPENAPI_FILE = CONTRACTS / "openapi" / "argus-api.yaml"


def _load(path: Path):
    text = path.read_text(encoding="utf-8")
    return yaml.safe_load(text) if path.suffix in {".yaml", ".yml"} else json.loads(text)


def cmd_check(_: argparse.Namespace) -> int:
    from app.core.contracts import validate_json

    problems: list[str] = []
    schemas = [p for p in CONTRACTS.rglob("*.json") if "examples" not in p.parts]
    for path in schemas:
        rel = path.relative_to(ROOT).as_posix()
        try:
            schema = _load(path)
            Draft202012Validator.check_schema(schema)
        except Exception as exc:  # noqa: BLE001
            problems.append(f"{rel}: invalid schema: {exc}")
            continue
        expected_id = "https://argus.local/" + path.relative_to(ROOT).as_posix()
        if schema.get("$id") != expected_id:
            problems.append(f"{rel}: $id must be {expected_id}")
        parts = path.relative_to(CONTRACTS).parts
        needs_example = parts[0] in {"events", "tools", "ml"} and "ws" not in parts and not path.name.startswith("_")
        if needs_example:
            example = path.parent / "examples" / (path.stem + ".example.json")
            if not example.exists():
                problems.append(f"{rel}: missing example {example.relative_to(ROOT).as_posix()}")

    for example in CONTRACTS.rglob("examples/*.example.json"):
        schema_path = example.parent.parent / example.name.replace(".example.json", ".json")
        rel = example.relative_to(ROOT).as_posix()
        if not schema_path.exists():
            problems.append(f"{rel}: no matching schema {schema_path.name}")
            continue
        try:
            validate_json(schema_path, _load(example))
        except Exception as exc:  # noqa: BLE001
            problems.append(f"{rel}: {exc}")

    for spec_path in sorted((CONTRACTS / "openapi").glob("*.yaml")):
        rel = spec_path.relative_to(ROOT).as_posix()
        try:
            spec = _load(spec_path)
        except Exception as exc:  # noqa: BLE001
            problems.append(f"{rel}: YAML error: {exc}")
            continue
        for key in ("openapi", "info", "paths"):
            if key not in (spec or {}):
                problems.append(f"{rel}: missing '{key}'")
        if spec and not str(spec.get("openapi", "")).startswith("3."):
            problems.append(f"{rel}: openapi must be 3.x")

    n_ex = len(list(CONTRACTS.rglob("examples/*.example.json")))
    n_api = len(list((CONTRACTS / "openapi").glob("*.yaml")))
    print(f"contracts: {len(schemas)} schemas, {n_ex} examples, {n_api} OpenAPI files")
    for p in problems:
        print(f"  FAIL {p}")
    print("OK" if not problems else f"{len(problems)} problem(s)")
    return 1 if problems else 0


def generate_specs() -> dict[Path, str]:
    from app.config import Settings
    from app.main import create_app
    from app.registry import discover

    app = create_app(Settings(database_url="sqlite+aiosqlite:///:memory:", log_json=False))
    spec = app.openapi()
    spec["info"]["description"] = "GENERATED by scripts/contracts.py export from backend/app. Do not hand-edit."
    files: dict[Path, str] = {OPENAPI_FILE: yaml.safe_dump(spec, sort_keys=False, allow_unicode=True, width=120)}
    for capability in discover():
        producer = getattr(capability.wiring, "contract_documents", None)
        if producer is None:
            continue
        for rel, doc in producer().items():
            full_doc = {"$schema": "https://json-schema.org/draft/2020-12/schema",
                        "$id": f"https://argus.local/contracts/{rel}",
                        "$comment": f"GENERATED from app ({capability.name}) models by scripts/contracts.py export. "
                                    "Do not hand-edit.",
                        **{k: v for k, v in doc.items() if k not in ("$schema", "$id")}}
            files[CONTRACTS / rel] = json.dumps(full_doc, indent=2, ensure_ascii=False) + "\n"
    return files


def cmd_export(args: argparse.Namespace) -> int:
    files = generate_specs()
    drift = []
    for path, text in files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            drift.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(text.encode("utf-8"))
    for path in drift:
        print(("DRIFT " if args.check else "wrote ") + path.relative_to(ROOT).as_posix())
    if args.check and drift:
        print("Generated contracts are out of date with the code. Run: uv run python scripts/contracts.py export")
        return 1
    print(f"{len(files)} generated contract file(s) {'checked' if args.check else 'up to date' if not drift else 'exported'}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check").set_defaults(func=cmd_check)
    ex = sub.add_parser("export")
    ex.add_argument("--check", action="store_true")
    ex.set_defaults(func=cmd_export)
    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
