#!/usr/bin/env python3
"""Cross-platform task runner. Works without make/bash (Windows friendly). Run from anywhere.

    python scripts/dev.py setup               uv sync + frontend install
    python scripts/dev.py env                 create .env from .env.example (if missing)
    python scripts/dev.py api                 backend in LITE mode (SQLite + in-memory bus), auto-seeded, :8000
    python scripts/dev.py web                 frontend dev server, :3000 (operator + supervisor areas)
    python scripts/dev.py up | down           full stack via Docker Compose
    python scripts/dev.py migrate             alembic upgrade head
    python scripts/dev.py revision -m "msg"   new (linear) migration, autogenerated from models
    python scripts/dev.py seed                demo data into the configured DB
    python scripts/dev.py sim [args...]       simulator, e.g. sim --scenario S1 --seed 42 --demo-g1
    python scripts/dev.py test [area]         backend tests (all, or backend/tests/<area>, e.g. twin)
    python scripts/dev.py lint                ruff (backend) + eslint/tsc (frontend)
    python scripts/dev.py contracts           export generated contracts + validate + regenerate frontend API types
    python scripts/dev.py check               everything CI runs
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "frontend"
PNPM = ["npx", "--yes", "pnpm@9"]
ALEMBIC = ["alembic", "-c", "backend/alembic.ini"]


def run(cmd: list[str], env: dict | None = None, cwd: Path = ROOT) -> int:
    print("$", " ".join(cmd), flush=True)
    exe = shutil.which(cmd[0]) or cmd[0]
    return subprocess.call([exe, *cmd[1:]], cwd=cwd, env={**os.environ, **(env or {})})


def uv(*args: str, env: dict | None = None) -> int:
    return run(["uv", "run", *args], env=env)


def pnpm(*args: str) -> int:
    if not (FRONTEND / "node_modules").exists() and args[:1] != ("install",):
        run([*PNPM, "install"], cwd=FRONTEND)
    return run([*PNPM, *args], cwd=FRONTEND)


LITE = {"APP_ENV": "lite", "DATABASE_URL": "sqlite+aiosqlite:///./.data/argus.db", "EVENT_BUS": "memory",
        "REDIS_URL": "", "DB_AUTO_CREATE": "true", "LOG_JSON": "false"}


def cmd_setup(_: list[str]) -> int:
    return run(["uv", "sync"]) or pnpm("install")


def cmd_env(_: list[str]) -> int:
    target = ROOT / ".env"
    if target.exists():
        print(".env already exists; leaving it alone")
        return 0
    shutil.copyfile(ROOT / ".env.example", target)
    print("wrote .env from .env.example")
    return 0


def cmd_api(args: list[str]) -> int:
    (ROOT / ".data").mkdir(exist_ok=True)
    if uv("python", "-m", "app.seed", env=LITE):
        return 1
    return uv("uvicorn", "app.main:create_app", "--factory", "--reload", "--reload-dir", "backend/app",
              "--port", "8000", *args, env=LITE)


def cmd_web(args: list[str]) -> int:
    return pnpm("dev", *args)


def cmd_up(args: list[str]) -> int:
    cmd_env([])
    return run(["docker", "compose", "up", "--build", "-d", *args])


def cmd_down(args: list[str]) -> int:
    return run(["docker", "compose", "down", *args])


def cmd_migrate(_: list[str]) -> int:
    return uv(*ALEMBIC, "upgrade", "head")


def cmd_revision(args: list[str]) -> int:
    import argparse

    p = argparse.ArgumentParser(prog="dev.py revision")
    p.add_argument("-m", "--message", required=True)
    p.add_argument("--no-autogenerate", action="store_true")
    a = p.parse_args(args)
    cmd = [*ALEMBIC, "revision", "-m", a.message]
    if not a.no_autogenerate:
        cmd.append("--autogenerate")
    print("Autogenerate compares models with the DB at DATABASE_URL: run `migrate` first. Review the file before committing.")
    return uv(*cmd)


def cmd_seed(_: list[str]) -> int:
    return uv("python", "-m", "app.seed")


def cmd_sim(args: list[str]) -> int:
    return uv("python", "-m", "app.iot.simulator", *args)


def cmd_test(args: list[str]) -> int:
    target = [f"backend/tests/{args[0]}", *args[1:]] if args and not args[0].startswith("-") else args
    return uv("pytest", *target)


def cmd_lint(_: list[str]) -> int:
    return uv("ruff", "check", "backend", "scripts") or pnpm("lint") or pnpm("typecheck")


def cmd_contracts(_: list[str]) -> int:
    return uv("python", "scripts/contracts.py", "export") or uv("python", "scripts/contracts.py", "check") or pnpm("generate")


def cmd_check(_: list[str]) -> int:
    steps = [
        lambda: uv("ruff", "check", "backend", "scripts"),
        lambda: uv("python", "scripts/contracts.py", "check"),
        lambda: uv("python", "scripts/contracts.py", "export", "--check"),
        lambda: uv("pytest", "-q"),
        lambda: pnpm("generate"),
        lambda: run(["git", "diff", "--exit-code", "--", "frontend/src/lib/api/generated"]),
        lambda: pnpm("lint"),
        lambda: pnpm("typecheck"),
        lambda: pnpm("build"),
    ]
    for step in steps:
        if code := step():
            return code
    print("all checks passed")
    return 0


COMMANDS = {name[4:]: fn for name, fn in globals().items() if name.startswith("cmd_")}


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        print(__doc__)
        return 1
    return COMMANDS[sys.argv[1]](sys.argv[2:])


if __name__ == "__main__":
    sys.exit(main())
