"""m00 platform initial

Revision ID: m00_0001
Revises: 
Create Date: 2026-09-23 15:23:39.269032
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.database  # noqa: F401  (custom column types)


revision: str = 'm00_0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('m00_platform',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('sites',
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('site_id', name=op.f('pk_sites'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('machines',
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('machine_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('engine_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name=op.f('fk_machines_site_id_sites')),
    sa.PrimaryKeyConstraint('machine_id', name=op.f('pk_machines')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_machines_serial_number'))
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_site_id'), ['site_id'], unique=False)

    op.create_table('operators',
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('experience_level', sa.String(length=16), nullable=False),
    sa.Column('certification_status', sa.String(length=16), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name=op.f('fk_operators_site_id_sites')),
    sa.PrimaryKeyConstraint('operator_id', name=op.f('pk_operators'))
    )
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operators_site_id'), ['site_id'], unique=False)

    op.create_table('user_site_scopes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name=op.f('fk_user_site_scopes_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_site_scopes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_id', name=op.f('pk_user_site_scopes'))
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('zone_type', sa.String(length=32), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name=op.f('fk_zones_site_id_sites')),
    sa.PrimaryKeyConstraint('zone_id', name=op.f('pk_zones'))
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_site_id'))

    op.drop_table('zones')
    op.drop_table('user_site_scopes')
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operators_site_id'))

    op.drop_table('operators')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_site_id'))

    op.drop_table('machines')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('sites')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
